# Generated by Django 4.0 on 2022-05-22 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_product_last_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_contact_information', to='api.user')),
            ],
        ),
    ]
