# Generated by Django 4.0 on 2022-05-22 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_usercontactinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_revision',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_reason', models.TextField(default='Is not', max_length=700)),
                ('report_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='reports',
            field=models.ManyToManyField(to='api.Report'),
        ),
    ]
