# Generated by Django 4.0 on 2022-05-28 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_user_has_module_perms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_module_perms',
        ),
    ]
